// examples/sveltekit/src/lib/components/ArticleCard.svelte
<script lang="ts">
  import { shapioAttr } from '@shapio/visual';
  import { articlePath, type Strings } from '../site';
  import type { Article } from '../types';
  import Byline from './Byline.svelte';
  import ResponsiveImage from './ResponsiveImage.svelte';

  type Props = { article: Article; locale: string; strings: Strings };
  let { article, locale, strings }: Props = $props();
</script>

<li class="card">
  {#if article.cover}
    <ResponsiveImage media={article.cover} sizes="(min-width: 48rem) 33vw, 100vw" />
  {/if}
  <h2 {...shapioAttr(article, 'title')}><a href={articlePath(locale, article.slug)}>{article.title}</a></h2>
  <Byline {article} {locale} {strings} />
  {#if article.excerpt}
    <p>{article.excerpt}</p>
  {/if}
</li>

// examples/next/src/components/ArticleCard/index.tsx
import { shapioAttr } from '@shapio/visual';
import Link from 'next/link';
import { articlePath, type Strings } from '../../lib/site';
import type { Article } from '../../lib/types';
import { Byline } from '../Byline';
import { ResponsiveImage } from '../ResponsiveImage';

type ArticleCardProps = { article: Article; locale: string; strings: Strings };

export const ArticleCard = ({ article, locale, strings }: ArticleCardProps) => (
  <li className="card">
    {article.cover ? <ResponsiveImage media={article.cover} sizes="(min-width: 48rem) 33vw, 100vw" /> : null}
    <h2 {...shapioAttr(article, 'title')}>
      <Link href={articlePath(locale, article.slug)}>{article.title}</Link>
    </h2>
    <Byline article={article} locale={locale} strings={strings} />
    {article.excerpt ? <p>{article.excerpt}</p> : null}
  </li>
);
