// examples/next/src/components/ArticleView/index.tsx
import { shapioAttr } from '@shapio/visual';
import { authorOf } from '../../lib/articles';
import type { Strings } from '../../lib/site';
import type { Article } from '../../lib/types';
import { Byline } from '../Byline';
import { ResponsiveImage } from '../ResponsiveImage';
import { RichText } from '../RichText';

type ArticleViewProps = { article: Article; locale: string; strings: Strings };

export const ArticleView = ({ article, locale, strings }: ArticleViewProps) => {
  const author = authorOf(article);
  return (
    <article className="article" lang={article.locale}>
      <header>
        <h1 {...shapioAttr(article, 'title')}>{article.title}</h1>
        <Byline article={article} locale={locale} strings={strings} />
      </header>
      {article.cover ? (
        <ResponsiveImage
          media={article.cover}
          sizes="(min-width: 48rem) 48rem, 100vw"
          eager
          className="cover"
          visual={shapioAttr(article, 'cover')}
        />
      ) : null}
      <RichText value={article.body} visual={shapioAttr(article, 'body')} />
      {author ? (
        <aside className="author">
          {author.avatar ? <ResponsiveImage media={author.avatar} sizes="4rem" className="avatar" /> : null}
          <div>
            <p className="author-name">{author.name}</p>
            {author.bio ? <p>{author.bio}</p> : null}
          </div>
        </aside>
      ) : null}
    </article>
  );
};

// examples/sveltekit/src/lib/components/ArticleView.svelte
<script lang="ts">
  import { shapioAttr } from '@shapio/visual';
  import { authorOf } from '../articles';
  import type { Strings } from '../site';
  import type { Article } from '../types';
  import Byline from './Byline.svelte';
  import ResponsiveImage from './ResponsiveImage.svelte';
  import RichText from './RichText.svelte';

  type Props = { article: Article; locale: string; strings: Strings };
  let { article, locale, strings }: Props = $props();
  const author = $derived(authorOf(article));
</script>

<article class="article" lang={article.locale}>
  <header>
    <h1 {...shapioAttr(article, 'title')}>{article.title}</h1>
    <Byline {article} {locale} {strings} />
  </header>
  {#if article.cover}
    <ResponsiveImage
      media={article.cover}
      sizes="(min-width: 48rem) 48rem, 100vw"
      eager
      class="cover"
      visual={shapioAttr(article, 'cover')}
    />
  {/if}
  <RichText value={article.body} visual={shapioAttr(article, 'body')} />
  {#if author}
    <aside class="author">
      {#if author.avatar}
        <ResponsiveImage media={author.avatar} sizes="4rem" class="avatar" />
      {/if}
      <div>
        <p class="author-name">{author.name}</p>
        {#if author.bio}
          <p>{author.bio}</p>
        {/if}
      </div>
    </aside>
  {/if}
</article>
